server:
  port: 8080
  host: "0.0.0.0"

database:
  host: ${DB_HOST:-postgres}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-postgres}
  password: ${DB_PASSWORD:-postgres}
  dbname: ${DB_NAME:-subscription_db}
  sslmode: ${DB_SSLMODE:-disable}

logging:
  level: ${LOG_LEVEL:-info}
  format: ${LOG_FORMAT:-json}
